//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TFAlgoritmosEntities : DbContext
    {
        public TFAlgoritmosEntities()
            : base("name=TFAlgoritmosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Destino> Destino { get; set; }
        public virtual DbSet<Origen> Origen { get; set; }
        public virtual DbSet<Origen_Destino> Origen_Destino { get; set; }
        public virtual DbSet<Padron_Destino> Padron_Destino { get; set; }
        public virtual DbSet<Padron_Origen> Padron_Origen { get; set; }
        public virtual DbSet<Padron_Origen_Destino> Padron_Origen_Destino { get; set; }
    }
}
