//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Padron_Origen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Padron_Origen()
        {
            this.Padron_Origen_Destino = new HashSet<Padron_Origen_Destino>();
        }
    
        public int COD_CEPA { get; set; }
        public string NOMBRE_CEPA { get; set; }
        public string NIVEL_CEPA { get; set; }
        public string FORMAS_CEPA { get; set; }
        public string DIRECCION_CEPA { get; set; }
        public string SUPERVISOR_CEPA { get; set; }
        public string PUEBLO_CEPA { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Padron_Origen_Destino> Padron_Origen_Destino { get; set; }
    }
}
