//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Padron_Origen_Destino
    {
        public int OrigenId { get; set; }
        public int DestinoId { get; set; }
        public double Distancia { get; set; }
    
        public virtual Padron_Destino Padron_Destino { get; set; }
        public virtual Padron_Origen Padron_Origen { get; set; }
    }
}
